version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "8080:8080"
  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - 27017:27017

